name: Auto Update Products

on:
  schedule:
    - cron: '42 17 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Git
        run: |
          git config user.name "MATI SUPPLIERS Auto-Update"
          git config user.email "actions@github.com"
      
      - name: Pull and rebase
        run: git pull origin main --rebase --autostash
      
      - name: Run update
        run: |
          npm install
          node generate-products.js
      
      - name: Commit and push
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || {
            git commit -m "🔄 Auto-update products [$(date +'%Y-%m-%d %H:%M:%S')]"
            git push origin main
          }
